filebeat.inputs:
  - type: container
    paths:
      - '/var/lib/docker/containers/6d81a5f28e4ea4c3ff7e3fca0109d2b3344ececde432dde103bee48949ad6f5c/*.log'

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

  - decode_json_fields:
      fields: ["message"]
      target: "json"
      overwrite_keys: true

output.logstash:
  hosts: ["logstash:5044"]

#output.elasticsearch:
#  hosts: ["es-hot:9200"]
#  indices:
#    - index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"

#output.console:
#  enabled: true

logging.json: true
logging.metrics.enabled: false
